server:
  port: 9995
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF8&socketTimeout=60000
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 100
#必须开启 不然feign hystrix降级无法使用
feign:
  hystrix:
    enabled: true
#设置某个包下的日志级别
logging:
  level:
    org.springframework.cloud.openfeign: debug
#    org:
#      springframework:
#        cloud:
#          openfeign: debug
env:
   dev8
#其他配置
girl:
  name: "guo"
  age: 22